title: "Schimmenti Personal Page"
author: "Vincenzo Maria Schimmenti"
email: "schimmenti_at_pks.mpg.de"
description: "A personal academic website showcasing research, publications, and projects."
baseurl: ""
url: "https://vicioms.github.io"
theme: slate
